[package]
name = "laplace_server"
version = "0.1.1"
authors = [
    "Alexander Mescheryakov <freecoder.xx@gmail.com>",
    "Noogen Team <info.noogen@gmail.com>",
]
edition = "2021"
license = "MIT"
repository = "https://github.com/noogen-projects/laplace"
description = "The server of the local-first web-application platform"

[dependencies]
actix = "0.13"
actix-easy-multipart = "3.0"
actix-files = "0.6"
actix-web = { version = "4.3", features = ["rustls"] }
actix-web-actors = "4.2"
borsh = { workspace = true }
bs58 = "0.5"
clap = { version = "4.0", features = ["derive"] }
config = "0.13"
const_format = "0.2"
derive_more = "0.99"
flexi_logger = "0.25"
futures = "0.3"
laplace_common = { path = "../laplace_common" }
laplace_wasm = { path = "../laplace_wasm" }
libp2p = { version = "0.51", features = [
    "async-std",
    "tcp",
    "dns",
    "mdns",
    "gossipsub",
    "websocket",
    "noise",
    "mplex",
    "yamux",
] }
log = "0.4"
rcgen = "0.10"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
ring = "0.16"
rusqlite = { version = "0.29", features = ["bundled"] }
rustls = "0.20"
rustls-pemfile = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.21", features = ["fs"] }
toml = "0.7"
wasmer = "3.2.0-alpha.1"
wasmer-wasi = "3.2.0-alpha.1"
zip = "0.6"
