[package]
name = "laplace_server"
version = "0.1.1"
authors = [
    "Alexander Mescheryakov <freecoder.xx@gmail.com>",
    "Noogen Team <info.noogen@gmail.com>",
]
edition = "2021"
license = "MIT"
repository = "https://github.com/noogen-projects/laplace"
description = "The server of the local-first web-application platform"

[dependencies]
actix = "0.13"
actix-easy-multipart = "2.1"
actix-files = "0.6"
actix-web = { version = "4.2", features = ["rustls"] }
actix-web-actors = "4.1"
anyhow = "1.0"
arc-swap = "1.5"
async-std = "1.12"
borsh = "0.9"
bs58 = "0.4"
clap = { version = "4.0", features = ["derive"] }
config = "0.13"
derive_more = "0.99"
flexi_logger = "0.24"
futures = "0.3"
laplace_common = { path = "../laplace_common" }
laplace_wasm = { path = "../laplace_wasm" }
libp2p = { version = "0.49", features = ["async-std", "tcp", "dns", "mdns", "gossipsub", "websocket", "noise", "mplex", "yamux"] }
log = "0.4"
rcgen = "0.10"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "rustls-tls"] }
ring = "0.16"
rusqlite = { version = "0.28", features = ["bundled"] }
rustls = "0.20"
rustls-pemfile = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
toml = "0.5"
wasmer = "2.3"
wasmer-wasi = "2.3"
zip = { git = "https://github.com/wyatt-herkamp/zip.git" } # Fix zstd dependency
