[http]
host = "127.0.0.1"
port = 8080
access_token = "24tpHRcbGKGYFGMYq66G3hfH8GQEYGTysXqiJyaCy9eR"
print_url = true

[p2p]
mdns_discovery_enabled = true

[log]
spec = "info,regalloc=warn,wasmer_compiler_cranelift=warn"

[lapps]
path = "lapps"
