[package]
name = "todo_server"
version = "0.1.0"
authors = [
    "Alexander Mescheryakov <freecoder.xx@gmail.com>",
    "Noogen Team <info.noogen@gmail.com>",
]
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/noogen-projects/dapla"
description = "The Todo d-app example"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
thiserror = "1.0"
serde_json = "1.0"
borsh = "0.9"
sql-builder = "3.1"
todo_common = { path = "../common" }
dapla_wasm = { path = "../../../dapla_wasm" }