[application]
title = "Todo"
enabled = true
description = "The Todo local-first web app example"
tags = ["example", "todo"]
access_token = "OTpFVytjgoRuUpoBACruBcBmxXmREVnmjFMhqAwfJdfQ8amoqkJxJncWZMVo9mGe"

[permissions]
required = ["database", "client_http"]
allowed = ["database", "client_http"]

[database]
path = "todos.db"
