[application]
title = "Todo"
enabled = true
session_token = "OTpFVytjgoRuUpoBACruBcBmxXmREVnmjFMhqAwfJdfQ8amoqkJxJncWZMVo9mGe"

[permissions]
required = ["database", "client_http"]
allowed = ["database", "client_http"]

[database]
path = "daps/todo/todos.db"
