[application]
title = "Chat"
enabled = true
description = "The Chat local-first web app example"
tags = ["example", "chat"]
access_token = "JDQmIY3pxSI28Y3U5x6BpTmnx0ojFp6Emc29zrEOrmA0bWJhZue97dJ4YNjxyERX"

[permissions]
required = ["client_http", "websocket", "tcp", "lapps_outgoing"]
allowed = ["client_http", "websocket", "tcp", "lapps_outgoing"]

[network.gossipsub]
addr = "/ip4/0.0.0.0/tcp/36598"
dial_ports = [36598, 36599]

[[lapp_requests]]
lapp_name = "sowa"

    [[lapp_requests.outgoing]]
    methods = ["get"]
    request = "account/.*"

    [[lapp_requests.outgoing]]
    methods = ["post"]
    request = "transfer/.*"
