[application]
title = "Chat"
enabled = true

[permissions]
required = ["client_http", "websocket", "tcp"]
allowed = ["client_http", "websocket", "tcp"]

[network.gossipsub]
addr = "/ip4/0.0.0.0/tcp/36598"
dial_ports = [36598, 36599]
